/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import FinishUI from "./View/FinishUI"
import RotateLoop from "./Libs/RotateLoop"
import GameUI from "./View/GameUI"
import UpdateGrade from "./Mod/UpdateGrade"
import Blink from "./Libs/Blink"
import LoadingUI from "./View/LoadingUI"
import UpDownLoop from "./Mod/UpDownLoop"
import SelectUI from "./View/SelectUI"
import ScaleLoop from "./Libs/ScaleLoop"
import StartUI from "./View/StartUI"
import SGBoxBottom from "./SGSDK/SGBoxBottom"
import SGScale from "./SGSDK/SGScale"
import SGRotate from "./SGSDK/SGRotate"
import SGBoxMiddle from "./SGSDK/SGBoxMiddle"
import SGHomeUI from "./SGSDK/SGHomeUI"
import SGRemen from "./SGSDK/SGRemen"
import SGSkin from "./SGSDK/SGSkin"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="SGScene/SGHomeUI.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("View/FinishUI.ts",FinishUI);
        reg("Libs/RotateLoop.ts",RotateLoop);
        reg("View/GameUI.ts",GameUI);
        reg("Mod/UpdateGrade.ts",UpdateGrade);
        reg("Libs/Blink.ts",Blink);
        reg("View/LoadingUI.ts",LoadingUI);
        reg("Mod/UpDownLoop.ts",UpDownLoop);
        reg("View/SelectUI.ts",SelectUI);
        reg("Libs/ScaleLoop.ts",ScaleLoop);
        reg("View/StartUI.ts",StartUI);
        reg("SGSDK/SGBoxBottom.ts",SGBoxBottom);
        reg("SGSDK/SGScale.ts",SGScale);
        reg("SGSDK/SGRotate.ts",SGRotate);
        reg("SGSDK/SGBoxMiddle.ts",SGBoxMiddle);
        reg("SGSDK/SGHomeUI.ts",SGHomeUI);
        reg("SGSDK/SGRemen.ts",SGRemen);
        reg("SGSDK/SGSkin.ts",SGSkin);
    }
}
GameConfig.init();