/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import SGBoxBottom from "./SGSDK/SGBoxBottom"
import SGHomeUI from "./SGSDK/SGHomeUI"
import SGRemen from "./SGSDK/SGRemen"
import FinishUI from "./View/FinishUI"
import RotateLoop from "./Libs/RotateLoop"
import GameUI from "./View/GameUI"
import UpdateGrade from "./Mod/UpdateGrade"
import Blink from "./Libs/Blink"
import LoadingUI from "./View/LoadingUI"
import UpDownLoop from "./Mod/UpDownLoop"
import SelectUI from "./View/SelectUI"
import ScaleLoop from "./Libs/ScaleLoop"
import StartUI from "./View/StartUI"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="FDScene/SGHomeUI.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("FanDong/Box1.ts",SGBoxBottom);
        reg("FanDong/HomeUI.ts",SGHomeUI);
        reg("FanDong/Remen.ts",SGRemen);
        reg("View/FinishUI.ts",FinishUI);
        reg("Libs/RotateLoop.ts",RotateLoop);
        reg("View/GameUI.ts",GameUI);
        reg("Mod/UpdateGrade.ts",UpdateGrade);
        reg("Libs/Blink.ts",Blink);
        reg("View/LoadingUI.ts",LoadingUI);
        reg("Mod/UpDownLoop.ts",UpDownLoop);
        reg("View/SelectUI.ts",SelectUI);
        reg("Libs/ScaleLoop.ts",ScaleLoop);
        reg("View/StartUI.ts",StartUI);
    }
}
GameConfig.init();