/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import BoxUI from "./View/BoxUI"
import FixNodeY from "./Libs/FixNodeY"
import FinishUI from "./View/FinishUI"
import CoinViewCrl from "./Crl/CoinViewCrl"
import GameUI from "./View/GameUI"
import LoadingUI from "./View/LoadingUI"
import SkinUI from "./View/SkinUI"
import StartUI from "./View/StartUI"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="MyScenes/FinishUI.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("View/BoxUI.ts",BoxUI);
        reg("Libs/FixNodeY.ts",FixNodeY);
        reg("View/FinishUI.ts",FinishUI);
        reg("Crl/CoinViewCrl.ts",CoinViewCrl);
        reg("View/GameUI.ts",GameUI);
        reg("View/LoadingUI.ts",LoadingUI);
        reg("View/SkinUI.ts",SkinUI);
        reg("View/StartUI.ts",StartUI);
    }
}
GameConfig.init();