/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Box1 from "./FanDong/Box1"
import HomeUI from "./FanDong/HomeUI"
import Remen from "./FanDong/Remen"
import VideoBanner from "./FanDong/VideoBanner"
import FinishUI from "./View/FinishUI"
import FixNodeY from "./Libs/FixNodeY"
import GameUI from "./View/GameUI"
import LoadingUI from "./View/LoadingUI"
import StartUI from "./View/StartUI"
import ScaleLoop from "./Libs/ScaleLoop"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="MyScenes/StartUI.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("FanDong/Box1.ts",Box1);
        reg("FanDong/HomeUI.ts",HomeUI);
        reg("FanDong/Remen.ts",Remen);
        reg("FanDong/VideoBanner.ts",VideoBanner);
        reg("View/FinishUI.ts",FinishUI);
        reg("Libs/FixNodeY.ts",FixNodeY);
        reg("View/GameUI.ts",GameUI);
        reg("View/LoadingUI.ts",LoadingUI);
        reg("View/StartUI.ts",StartUI);
        reg("Libs/ScaleLoop.ts",ScaleLoop);
    }
}
GameConfig.init();